;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-copy-region
        ignore
        keyboard-escape-quit
        keyboard-quit
        ))

(setq mc/cmds-to-run-once
      '(
        cua--prefix-override-handler
        cua-set-rectangle-mark
        mouse-set-region
        widget-button-click
        ))
